version: "3.2"
services:
    # webapi:
    #    build: .
    #    ports:
    #        - "5000:5000"
    #    depends_on:
    #        - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Suporte_123456"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"